// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN4ppRjhU0fLksMm973MimOufaWEUwRWs',
    appId: '1:872252600503:web:ac3ee8e724502faa349d32',
    messagingSenderId: '872252600503',
    projectId: 'ai-quiz-74345',
    authDomain: 'ai-quiz-74345.firebaseapp.com',
    storageBucket: 'ai-quiz-74345.firebasestorage.app',
    measurementId: 'G-BMKLJFVQNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFWgqjvBU7k9V64Cy0uPiYHajmqPT3f24',
    appId: '1:872252600503:android:e213ddd07438248c349d32',
    messagingSenderId: '872252600503',
    projectId: 'ai-quiz-74345',
    storageBucket: 'ai-quiz-74345.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfyhxEx7X-dPohPLmlX2k6D7eIIK_D7wE',
    appId: '1:872252600503:ios:e103d4cd9832707e349d32',
    messagingSenderId: '872252600503',
    projectId: 'ai-quiz-74345',
    storageBucket: 'ai-quiz-74345.firebasestorage.app',
    iosBundleId: 'com.ProgramEz.Quizzit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfyhxEx7X-dPohPLmlX2k6D7eIIK_D7wE',
    appId: '1:872252600503:ios:e103d4cd9832707e349d32',
    messagingSenderId: '872252600503',
    projectId: 'ai-quiz-74345',
    storageBucket: 'ai-quiz-74345.firebasestorage.app',
    iosBundleId: 'com.ProgramEz.Quizzit',
  );
}
